import { Track } from '../types';

export const MOCK_TRACKS: Track[] = [
    {
        id: '1',
        title: 'Midnight City',
        artist: 'M83',
        album: 'Hurry Up, We\'re Dreaming',
        coverUrl: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=300&q=80',
        duration: 243,
        streamUrl: '', // Mock
        genre: ['Electronic', 'Synthpop'],
        bpm: 105,
        energy: 0.8,
        valence: 0.6,
        popularity: 90
    },
    {
        id: '2',
        title: 'Weightless',
        artist: 'Marconi Union',
        album: 'Weightless (Ambient Transmissions Vol. 2)',
        coverUrl: 'https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=300&q=80',
        duration: 480,
        streamUrl: '',
        genre: ['Ambient', 'Chill'],
        bpm: 60,
        energy: 0.2,
        valence: 0.4,
        popularity: 75
    },
    {
        id: '3',
        title: 'Stronger',
        artist: 'Kanye West',
        album: 'Graduation',
        coverUrl: 'https://images.unsplash.com/photo-1549213821-4708d624e1d1?w=300&q=80',
        duration: 311,
        streamUrl: '',
        genre: ['Hip Hop', 'Rap'],
        bpm: 104,
        energy: 0.95,
        valence: 0.7,
        popularity: 95
    },
    {
        id: '4',
        title: 'Lo-Fi Study Beats',
        artist: 'Chill Cow',
        album: 'Study Session',
        coverUrl: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?w=300&q=80',
        duration: 180,
        streamUrl: '',
        genre: ['Lo-Fi', 'Instrumental'],
        bpm: 80,
        energy: 0.4,
        valence: 0.5,
        popularity: 85
    },
    {
        id: '5',
        title: 'Mr. Brightside',
        artist: 'The Killers',
        album: 'Hot Fuss',
        coverUrl: 'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=300&q=80',
        duration: 222,
        streamUrl: '',
        genre: ['Rock', 'Indie'],
        bpm: 148,
        energy: 0.9,
        valence: 0.3,
        popularity: 98
    },
    {
        id: '6',
        title: 'Clair de Lune',
        artist: 'Claude Debussy',
        album: 'Suite bergamasque',
        coverUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384ebd?w=300&q=80',
        duration: 300,
        streamUrl: '',
        genre: ['Classical'],
        bpm: 50,
        energy: 0.1,
        valence: 0.3,
        popularity: 88
    },
    {
        id: '7',
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        coverUrl: 'https://images.unsplash.com/photo-1619983081563-430f63602796?w=300&q=80',
        duration: 200,
        streamUrl: '',
        genre: ['Pop', 'Synthwave'],
        bpm: 171,
        energy: 0.9,
        valence: 0.8,
        popularity: 99
    },
    {
        id: '8',
        title: 'Thunderstruck',
        artist: 'AC/DC',
        album: 'The Razors Edge',
        coverUrl: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=300&q=80',
        duration: 292,
        streamUrl: '',
        genre: ['Rock', 'Hard Rock'],
        bpm: 134,
        energy: 0.98,
        valence: 0.7,
        popularity: 92
    },
    {
        id: '9',
        title: 'Rain on the Roof',
        artist: 'Nature Sounds',
        album: 'Sleep Sounds',
        coverUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=300&q=80',
        duration: 600,
        streamUrl: '',
        genre: ['Nature', 'Sleep'],
        bpm: 0,
        energy: 0.05,
        valence: 0.5,
        popularity: 60
    }
];
