import React, { useState } from 'react';
import { SeedSelector } from './SeedSelector';
import { RecommendationEngine } from '../../services/recommendationEngine';
import { SpotifyClient } from '../../services/spotifyClient';
import { Track, SpotifyTrack } from '../../types';
import { Sliders, Sparkles, Save, Play, RefreshCw, Zap, Smile, Activity } from 'lucide-react';
import { toast } from '../UI/Toast';
import { usePlayer } from '../../store/PlayerContext';

import { TrendService } from '../../services/trendService';
import { HYPE_ARTISTS } from '../../constants/artists';

type Mode = 'vibes' | 'trends';

export const Generator: React.FC = () => {
    const [mode, setMode] = useState<Mode>('vibes');

    // Vibe State
    const [seeds, setSeeds] = useState<SpotifyTrack[]>([]);
    const [energy, setEnergy] = useState(0.6);
    const [valence, setValence] = useState(0.5);
    const [bpm, setBpm] = useState(120);

    // Trend State
    const [trendGenre, setTrendGenre] = useState('Hip Hop');
    const [useHypeFilter, setUseHypeFilter] = useState(true);

    // Shared State
    const [results, setResults] = useState<Track[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [isSaving, setIsSaving] = useState(false);

    // Player context to play preview
    const { playTrack } = usePlayer();

    // ... (toggleSeed logic remains the same)
    const toggleSeed = (track: SpotifyTrack) => {
        if (seeds.find(s => s.id === track.id)) {
            setSeeds(seeds.filter(s => s.id !== track.id));
        } else {
            if (seeds.length >= 5) {
                toast.show('Max 5 seeds allowed', 'error');
                return;
            }
            setSeeds([...seeds, track]);
        }
    };

    const handleGenerate = async () => {
        setIsGenerating(true);
        setResults([]);
        try {
            let tracks: Track[] = [];

            if (mode === 'vibes') {
                if (seeds.length === 0) {
                    toast.show('Select at least 1 seed track', 'warning');
                    setIsGenerating(false);
                    return;
                }
                const seedTracks = seeds.map(s => ({ id: s.id } as Track));
                tracks = await RecommendationEngine.generatePlaylistFromSeeds(
                    seedTracks,
                    { energy, valence, bpm }
                );
            } else {
                // Trend Hunter Logic
                tracks = await TrendService.huntTrends(trendGenre, useHypeFilter);
            }

            setResults(tracks);
            if (tracks.length === 0) toast.show('No tracks found for these settings', 'info');
        } catch (error) {
            toast.show('Failed to generate playlist', 'error');
            console.error(error);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSave = async () => {
        if (results.length === 0) return;
        setIsSaving(true);
        try {
            // 1. Get User ID
            const me = await SpotifyClient.getCurrentUser();

            const playlistName = mode === 'vibes'
                ? `Vibe: ${energy > 0.7 ? 'High Energy' : 'Chill'} Mix`
                : `Trend Hunter: ${trendGenre} ${useHypeFilter ? '(Hype)' : ''}`;

            const playlist = await SpotifyClient.createPlaylist(me.id, playlistName, `Generated by Zuno based on ${mode === 'vibes' ? seeds.map(s => s.name).join(', ') : 'Zuno Trend Hunter'}`);

            await SpotifyClient.addTracksToPlaylist(playlist.id, results.map(t => `spotify:track:${t.id}`));

            toast.show(`Playlist "${playlistName}" saved to Spotify!`, 'success');

        } catch (error) {
            console.error(error);
            toast.show('Failed to save playlist', 'error');
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <div className="p-6 pb-32 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500">
            <header className="flex items-center justify-between">
                <div>
                    <h1 className="text-4xl font-bold text-white mb-2 flex items-center gap-3">
                        <Sliders className="text-zuno-accent" />
                        Generator
                    </h1>
                    <p className="text-zuno-muted">Craft your perfect playlist using audio science or trend hunting.</p>
                </div>

                {/* Mode Switcher */}
                <div className="flex bg-white/5 p-1 rounded-xl border border-white/10">
                    <button
                        onClick={() => setMode('vibes')}
                        className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${mode === 'vibes' ? 'bg-zuno-accent text-black shadow-lg' : 'text-white/60 hover:text-white'}`}
                    >
                        Vibe Mixer
                    </button>
                    <button
                        onClick={() => setMode('trends')}
                        className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${mode === 'trends' ? 'bg-zuno-accent text-black shadow-lg' : 'text-white/60 hover:text-white'}`}
                    >
                        Trend Hunter
                    </button>
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Left: Controls */}
                <div className="lg:col-span-1 space-y-8">

                    {mode === 'vibes' ? (
                        <>
                            {/* Seeds */}
                            <div className="bg-zuno-card/50 p-6 rounded-2xl border border-white/5 backdrop-blur-md">
                                <SeedSelector selectedSeeds={seeds} onToggleSeed={toggleSeed} />
                            </div>

                            {/* Sliders */}
                            <div className="bg-zuno-card/50 p-6 rounded-2xl border border-white/5 backdrop-blur-md space-y-6">
                                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                                    <Activity size={20} className="text-blue-400" />
                                    Fine Tune
                                </h3>

                                <div className="space-y-3">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-white flex items-center gap-2"><Zap size={14} /> Energy</span>
                                        <span className="text-zuno-accent font-mono">{Math.round(energy * 100)}%</span>
                                    </div>
                                    <input
                                        type="range" min="0" max="1" step="0.05"
                                        value={energy} onChange={e => setEnergy(Number(e.target.value))}
                                        className="w-full accent-zuno-accent h-2 bg-white/10 rounded-lg appearance-none cursor-pointer touch-none"
                                        style={{
                                          WebkitAppearance: 'none',
                                          touchAction: 'none',
                                        }}
                                    />
                                </div>

                                <div className="space-y-3">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-white flex items-center gap-2"><Smile size={14} /> Positivity (Valence)</span>
                                        <span className="text-purple-400 font-mono">{Math.round(valence * 100)}%</span>
                                    </div>
                                    <input
                                        type="range" min="0" max="1" step="0.05"
                                        value={valence} onChange={e => setValence(Number(e.target.value))}
                                        className="w-full accent-purple-500 h-2 bg-white/10 rounded-lg appearance-none cursor-pointer touch-none"
                                        style={{
                                          WebkitAppearance: 'none',
                                          touchAction: 'none',
                                        }}
                                    />
                                </div>

                                <div className="space-y-3">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-white flex items-center gap-2"><Activity size={14} /> Tempo (BPM)</span>
                                        <span className="text-orange-400 font-mono">{bpm}</span>
                                    </div>
                                    <input
                                        type="range" min="60" max="180" step="5"
                                        value={bpm} onChange={e => setBpm(Number(e.target.value))}
                                        className="w-full accent-orange-500 h-2 bg-white/10 rounded-lg appearance-none cursor-pointer touch-none"
                                        style={{
                                          WebkitAppearance: 'none',
                                          touchAction: 'none',
                                        }}
                                    />
                                </div>
                            </div>
                        </>
                    ) : (
                        /* Trend Hunter Controls */
                        <div className="bg-zuno-card/50 p-6 rounded-2xl border border-white/5 backdrop-blur-md space-y-6">
                            <h3 className="text-lg font-bold text-white flex items-center gap-2">
                                <Sparkles size={20} className="text-pink-400" />
                                Trend Settings
                            </h3>

                            <div className="space-y-2">
                                <label className="text-sm text-zuno-muted">Target Genre / Scene</label>
                                <input
                                    type="text"
                                    value={trendGenre}
                                    onChange={(e) => setTrendGenre(e.target.value)}
                                    className="w-full bg-black/40 border border-white/10 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-zuno-accent"
                                    placeholder="e.g. Trap, Hyperpop, UK Drill"
                                />
                            </div>

                            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl border border-white/5">
                                <div>
                                    <p className="text-white font-medium">Hype Beast Mode</p>
                                    <p className="text-xs text-zuno-muted">Filter using "The List" (Drake, Future, etc)</p>
                                </div>
                                <button
                                    onClick={() => setUseHypeFilter(!useHypeFilter)}
                                    className={`w-12 h-7 rounded-full transition-colors relative ${useHypeFilter ? 'bg-zuno-accent' : 'bg-white/10'}`}
                                >
                                    <div className={`w-5 h-5 bg-white rounded-full shadow-md absolute top-1 transition-transform ${useHypeFilter ? 'left-6' : 'left-1'}`} />
                                </button>
                            </div>

                            <div className="p-4 bg-blue-500/10 rounded-xl border border-blue-500/20 text-xs text-blue-200">
                                <p>This mode simulates the "Spotify Playlist Generator" logic by fetching trending tracks and filtering against a curated hype list.</p>
                            </div>
                        </div>
                    )}

                    <button
                        onClick={handleGenerate}
                        disabled={isGenerating || (mode === 'vibes' && seeds.length === 0)}
                        className="w-full py-4 bg-white text-black font-bold rounded-xl hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-white/10"
                    >
                        {isGenerating ? <RefreshCw className="animate-spin" /> : (mode === 'vibes' ? <Sparkles /> : <Zap />)}
                        {mode === 'vibes' ? 'Generate Mix' : 'Hunt Trends'}
                    </button>

                </div>

                {/* Right: Results */}
                <div className="lg:col-span-2">
                    {results.length > 0 ? (
                        <div className="space-y-4 animate-in slide-in-from-bottom duration-500">
                            <div className="flex items-center justify-between">
                                <h3 className="text-xl font-bold text-white">Generated Mix ({results.length} tracks)</h3>
                                <button
                                    onClick={handleSave}
                                    disabled={isSaving}
                                    className="px-4 py-2 bg-zuno-accent text-black font-bold rounded-lg hover:bg-zuno-accent/90 flex items-center gap-2 text-sm transition-colors"
                                >
                                    {isSaving ? <RefreshCw size={16} className="animate-spin" /> : <Save size={16} />}
                                    Save to Spotify
                                </button>
                            </div>

                            <div className="grid gap-2">
                                {results.map((track, i) => (
                                    <div key={track.id} className="group flex items-center gap-4 p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-colors border border-white/5 hover:border-white/10">
                                        <span className="text-white/40 font-mono w-6 text-center text-sm">{i + 1}</span>
                                        <div className="relative">
                                            <img src={track.coverUrl} className="w-10 h-10 rounded shadow-md" alt="" />
                                            <button
                                                onClick={() => playTrack(track, results)}
                                                className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                                            >
                                                <Play size={16} className="text-white" fill="white" />
                                            </button>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h4 className="text-white font-medium truncate">{track.title}</h4>
                                            <p className="text-zuno-muted text-sm truncate">{track.artist}</p>
                                        </div>
                                        <span className="text-white/40 text-xs font-mono">
                                            {Math.floor(track.duration / 60)}:{Math.floor(track.duration % 60).toString().padStart(2, '0')}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-center p-12 text-white/20 border-2 border-dashed border-white/5 rounded-2xl">
                            {mode === 'vibes' ? <Sparkles size={48} className="mb-4 opacity-50" /> : <Zap size={48} className="mb-4 opacity-50" />}
                            <h3 className="text-xl font-bold text-white/40 mb-2">Ready to Create</h3>
                            <p>{mode === 'vibes' ? 'Select seeds and adjust the sliders to generate your perfect vibe.' : 'Enter a genre and hit Hunt to find trending hype tracks.'}</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};
